nome = input("Qual é o seu nome? ")
idade = input("Qual é a sua idade? ")
profissao = input("Qual é a sua profissão? ")
print("==============================")
print("Olá", nome + "!")
print("Você tem", idade, "anos")
print("Sua profissão é", profissao)
print("==============================")